checkdjango/authapp/urls.py
import authapp.views as authapp
from django.urls import path

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
]

checkdjango/basketapp/urls.py
import basketapp.views as basketapp


from django.contrib import admin
from django.urls import path, include

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    path('add/<int:songe_id>/', basketapp.add, name='add'),
    path('remove/<int:songe_basket_id>/', basketapp.remove, name='remove'),


]

checkdjango/checkapp/urls.py
import checkapp.views as checkapp


from django.contrib import admin
from django.urls import path, include

app_name = 'checkapp'

urlpatterns = [
    path('', checkapp.index),
    path('catalog/', checkapp.catalog, name='catalog'),
    path('catalog/category/<int:pk>/', checkapp.group, name='group'),
    path('catalog/category/album/<int:pk>/', checkapp.album, name='album'),
    path('catalog/category/album/song/<int:pk>/', checkapp.song, name='song'),
    path('catalog/category/album/song/song_page/<int:songe_pk>/', checkapp.song_page, name='song_page'),




]

checkdjango/checkdjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [


    path('', include('checkapp.urls', namespace='main')),

    path('auth/', include('authapp.urls', namespace='auth')),

    path('catalog/', include('checkapp.urls', namespace='catalog')),

    path('basket/', include('basketapp.urls', namespace='basket')),

    path('admin/', admin.site.urls),
]

checkdjango/authapp/models.py
from django.db import models





# Create your models here.

checkdjango/basketapp/models.py
from django.contrib.auth.models import User
from django.db import models

from checkapp.models import Song


class SongBasket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    songe = models.ForeignKey(Song, on_delete=models.CASCADE)
    added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.added.strftime("%Y.%m.%d %H:%M")}: {self.songe.name}'

    def to_html(self):
        return f'<i>{self.added.strftime("%Y.%m.%d %H:%M")}</i>: <b>{self.songe.name}</b>'

checkdjango/checkapp/models.py
from django.db import models
import datetime


class Category(models.Model):
    name = models.CharField(max_length=128)
    desc = models.TextField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

class Group(models.Model):
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    desc = models.TextField(blank=True)
    age = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Album(models.Model):
    category = models.ForeignKey(Group,
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to=None, default=100, verbose_name="Изображение")
    desc = models.TextField(blank=True)
    number_of_songs = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Альбом'
        verbose_name_plural = 'Альбомы'

class Song(models.Model):
    category = models.ForeignKey(Album,
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    time = models.TimeField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Песня'
        verbose_name_plural = 'Песни'

class Clips(models.Model):
    category = models.ForeignKey(Song,
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    desc = models.TextField(blank=True)
    time = models.TimeField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Клип'
        verbose_name_plural = 'Клипы'

checkdjango/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name',
                  'password1', 'password2', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'
            item.help_text = ''

checkdjango/authapp/views.py
import django.contrib.auth as auth
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from authapp.forms import LoginForm, RegisterForm


def login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            auth.login(request, form.get_user())
            return HttpResponseRedirect('/')
    else:
        form = LoginForm()

    context = {
        'page_title': 'авторизация',
        'form': form,
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        form = RegisterForm()

    context = {
        'page_title': 'регистрация',
        'form': form,
    }
    return render(request, 'authapp/register.html', context)

checkdjango/basketapp/views.py
from basketapp.models import SongBasket
from checkapp.models import Song
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render

from django.urls import reverse



def index(request):
    items = SongBasket.objects.filter(user=request.user)
    context = {
        'object_list': items,
    }

    return render(request, 'basketapp/index.html', context)


def add(request, songe_id):
    songe = Song.objects.get(pk=songe_id)
    SongBasket.objects.get_or_create(
        user=request.user,
        #songe_id=songe_id
        songe=songe
    )
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    #return HttpResponseRedirect(
    #   reverse('checkapp:song_page',
    #           kwargs={'songe_pk': songe.songe_id})
    #)

def remove(request, songe_basket_id):
    if request.is_ajax():
        item = SongBasket.objects.get(id=songe_basket_id)
        item.delete()
        # return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        return JsonResponse({'status': 'ok',
                             'songe_basket_id': songe_basket_id})

checkdjango/checkapp/views.py
from django.shortcuts import render

from checkapp.models import Category, Group, Album, Song, Clips


def catalog(request):
    categories = Category.objects.all()
    context = {
        'categories': categories,
        'page_title': 'каталог'
    }

    return render(request, 'checkapp/catalog.html', context)


def index(request):
    return render(request, 'checkapp/index.html')


def group(request, pk):
    Groupes = Group.objects.filter(category_id=pk)
    context = {
        'Groupes': Groupes,
        'page_title': 'страница групп'
    }
    return render(request, 'checkapp/group.html', context)


def album(request, pk):
    albumes = Album.objects.filter(category_id=pk)
    context = {
        'albumes': albumes,
        'page_title': 'страница альбомов'
    }
    return render(request, 'checkapp/album.html', context)


def song(request, pk):
    songes = Song.objects.filter(category_id=pk)
    context = {
        'songes': songes,
        'page_title': 'страница песен'
    }
    return render(request, 'checkapp/song.html', context)


def song_page(request, songe_pk):
    song = Song.objects.get(pk=songe_pk)
    context = {
        'song': song,
        'page_title': 'страница песен'
    }
    return render(request, 'checkapp/song_page.html', context)

checkdjango/authapp/templates/authapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|default:"аутентификация"|capfirst }}</title>
    {% block css %}
        <link rel="stylesheet" href="/static/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/css/main.css">
    {% endblock %}
    {% block js %}
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script src="/static/js/jquery-3.2.1.min.js"></script>
        <script src="/static/js/bootstrap.min.js"></script>
    {% endblock %}
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

checkdjango/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}

{% block content %}
    <div class="login-form">
        <div class="form-title">Вход в систему</div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit"
                   class="btn btn-success form-control"
                   value="войти">
        </form>
        <br>
        <a class="btn btn-info form-control" href="{% url 'auth:register' %}">
            зарегистрироваться
        </a>
    </div>
{% endblock %}

checkdjango/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}

{% block content %}
    <div class="register-form">
        <div class="form-title">Регистрация</div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit"
                   class="btn btn-success form-control"
                   value="зарегистрироваться">
        </form>
    </div>
{% endblock %}

checkdjango/basketapp/templates/basketapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Главная</title>
    {% block css %}
        <link rel="stylesheet" href="/static/css/main.css">
        <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    {% endblock %}
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
       <script src="/static/js/jquery-3.2.1.min.js"></script>
       <script src="/static/js/bootstrap.min.js"></script>
    {% block js %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-dark bg-dark">

    <a class="navbar-brand" href="/">Главная</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse" id="navbarToggleExternalContent">
       <div class="bg-dark p-4">
         <!--    <ul class= "navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active"> -->
                    <a class="nav-link" href="{% url 'main:catalog' %}">Категория </a>
      <!--          </li>
                <li class="nav-item"> -->
                    <a class="nav-link" href="/basket/">Корзина</a>
      <!--          </li>
                <li class="nav-item"> -->
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'auth:logout' %}">Выйти</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'auth:login' %}">Войти</a>
                    {% endif %}
      <!--          </li>
            </ul> -->
        </div>
    </div>
</nav>



{% block content %}
{% endblock %}
</body>
</html>

checkdjango/basketapp/templates/basketapp/index.html
{% extends 'basketapp/base.html' %}

{% block content %}



    <div class="basket">
        <h2>Ваши песни, {{ user.username|capfirst }}</h2>
        <ul>
            {% for item in object_list %}
                <li class="basket-item-{{ item.pk }}">
                {{ item.to_html|safe }}
                    <a href="{% url 'basket:remove' item.pk %}"
                        class="btn btn-danger remove_basket">
                        удалить
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

checkdjango/checkapp/templates/checkapp/album.html
{% extends 'checkapp/base.html' %}

{% block content %}
    <h1>Страница Альбомов</h1>
    <div class="courses-menu">
        <ul>
            {% for item in albumes %}
                <li class="list-group-item list-group-item-warning">
                    <a href="{% url 'main:song' item.pk %}">
                        {{ item }}
                    </a>
                </li>
            {% endfor %}
        </ul>

    </div>
{% endblock %}

checkdjango/checkapp/templates/checkapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Главная</title>
    {% block css %}
        <link rel="stylesheet" href="/static/css/main.css">
        <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    {% endblock %}
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
       <script src="/static/js/jquery-3.2.1.min.js"></script>
       <script src="/static/js/bootstrap.min.js"></script>
    {% block js %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-dark bg-dark">

    <a class="navbar-brand" href="/">Главная</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse" id="navbarToggleExternalContent">
       <div class="bg-dark p-4">
         <!--    <ul class= "navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active"> -->
                    <a class="nav-link" href="{% url 'main:catalog' %}">Категория </a>
      <!--          </li>
                <li class="nav-item"> -->
                    <a class="nav-link" href="/basket/">Корзина</a>
      <!--          </li>
                <li class="nav-item"> -->
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'auth:logout' %}">Выйти</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'auth:login' %}">Войти</a>
                    {% endif %}
      <!--          </li>
            </ul> -->
        </div>
    </div>
</nav>



{% block content %}
{% endblock %}
</body>
</html>

checkdjango/checkapp/templates/checkapp/catalog.html
{% extends 'checkapp/base.html' %}

{% block content %}
    <h1>Каталог</h1>
    <div >
        <ul>
            {% for item in categories %}
                <li class="list-group-item list-group-item-primary">
                    <a href="{% url 'main:group' item.pk %}">
                        {{ item }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

checkdjango/checkapp/templates/checkapp/group.html
{% extends 'checkapp/base.html' %}

{% block content %}
    <h1>Страница групп</h1>
    <div class="courses-menu">
        <ul>
            {% for item in Groupes %}
                <li class="list-group-item list-group-item-danger">
                    <a href="{% url 'main:album' item.pk %}">
                        {{ item }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

checkdjango/checkapp/templates/checkapp/index.html
{% extends 'checkapp/base.html' %}

{% block content %}
    <h1>Вы вошли на сайт</h1>
{% endblock %}

checkdjango/checkapp/templates/checkapp/song.html
{% extends 'checkapp/base.html' %}

{% block content %}
    <h1>Страница Песен</h1>
    <div class="songes-menu">
        <ul>
            {% for item in songes %}
                <li class="list-group-item list-group-item-success">
                    <a href="{% url 'main:song_page' item.pk %}">
                        {{ item }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

checkdjango/checkapp/templates/checkapp/song_page.html
{% extends 'checkapp/base.html' %}


{% block content %}
    <h1>Песня</h1>
    <p class="songes-name">
        {{ song.name }}
    </p>
    <p class="songes-desc">
        описание: {{ song.desc }}
    </p>
    <p class="songes-hours">
        часов: {{ song.time }}
    </p>
    <a href="{% url 'basket:add' song.id %}"
       class="btn btn-success">
        Купить
    </a>
{% endblock %}